name: Continuous Persistent VPS with Filebase Backup

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip sudo net-tools neofetch rsync zip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS CLI for Filebase
        run: |
          aws configure set aws_access_key_id ${{ secrets.FILEBASE_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.FILEBASE_SECRET_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.s3.endpoint_url https://${{ secrets.FILEBASE_ENDPOINT }}

      - name: Download backup from Filebase (if any)
        run: |
          aws s3 cp s3://${{ secrets.FILEBASE_BUCKET }}/full-backup.zip ./ || echo "No backup found"

      - name: Restore backup if downloaded
        run: |
          if [ -f full-backup.zip ]; then
            unzip -o full-backup.zip -d /
            echo "Backup restored."
          else
            echo "No backup to restore."
          fi

      - name: Set hostname to biralo
        run: sudo hostnamectl set-hostname biralo

      - name: Install Tailscale official script
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}" --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Show Tailscale IP
        run: |
          echo "Tailscale IPv4:"
          tailscale ip -4 || echo "Tailscale IP not found"

      - name: Backup ENTIRE VPS (lightweight example)
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/ || true
          sudo rsync -aAX /home /etc /var/lib /opt/vps-backup/full-system/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r full-backup.zip /opt/vps-backup

      - name: Upload backup to Filebase
        run: |
          aws s3 cp full-backup.zip s3://${{ secrets.FILEBASE_BUCKET }}/full-backup.zip

      - name: Sleep to keep VPS alive
        run: sleep 21600
